#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/gcc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch i386 -O3 -fomit-frame-pointer -DL_ENDIAN"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Tue Sep 14 09:22:31 CST 2010"
#endif
